// Auto-generated by synctypes script
// DO NOT EDIT THIS FILE MANUALLY
// Run 'npm run synctypes' to regenerate

export interface StrapiMediaAttributes {
  name: string;
  alternativeText?: string | null;
  caption?: string | null;
  width?: number;
  height?: number;
  formats?: any;
  hash: string;
  ext?: string;
  mime: string;
  size: number;
  url: string;
  previewUrl?: string | null;
  provider: string;
  provider_metadata?: any | null;
  createdAt: string;
  updatedAt: string;
}

export interface StrapiMediaData {
  id: number;
  attributes: StrapiMediaAttributes;
}

export interface StrapiArticleAttributes {
  title: string;
  content: string;
  publishedAt: string;
  createdAt: string;
  updatedAt: string;
  cover?: StrapiMediaData | null;
  [key: string]: any;
}

export interface StrapiArticle {
  id: number;
  attributes: StrapiArticleAttributes;
}

export interface StrapiCollectionData<T> {
  data: T[];
  meta?: {
    pagination?: {
      page: number;
      pageSize: number;
      pageCount: number;
      total: number;
    };
  };
}

export interface StrapiSingleData<T> {
  data: T | null;
  meta?: Record<string, any>;
}

